# Feature Engineering & Data Preprocessing

## Objective

The objective of this notebook is to prepare the cleaned customer churn dataset for machine learning.

The following preprocessing steps are performed:

- Create a Machine Learning dataset
- Remove unnecessary and leakage columns
- Separate features and target variable
- Encode categorical variables
- Split data into training and testing sets
- Scale numerical features (where required)

The final output of this notebook will be a machine learning-ready dataset that can be used to build churn prediction models.

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/cleaned/Telco_customer_churn_clean.csv")

In [3]:
df.shape

(7043, 30)

In [4]:
df.head()

,CustomerID,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,No,No,No,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,No,No,Yes,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,No,No,Yes,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,No,Yes,Yes,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,No,No,Yes,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   City               7043 non-null   str
 2   Zip Code           7043 non-null   int64
 3   Lat Long           7043 non-null   str
 4   Latitude           7043 non-null   float64
 5   Longitude          7043 non-null   float64
 6   Gender             7043 non-null   str
 7   Senior Citizen     7043 non-null   str
 8   Partner            7043 non-null   str
 9   Dependents         7043 non-null   str
 10  Tenure Months      7043 non-null   int64
 11  Phone Service      7043 non-null   str
 12  Multiple Lines     7043 non-null   str
 13  Internet Service   7043 non-null   str
 14  Online Security    7043 non-null   str
 15  Online Backup      7043 non-null   str
 16  Device Protection  7043 non-null   str
 17  Tech Support       7043 non-null   str
 18  Streaming TV       7043 non-null   str
 19  Streaming Movies   7043 non-null   str
 20  Contract           7043 non-null   str
 21  Paperless Billing  7043 non-null   str
 22  Payment Method     7043 non-null   str
 23  Monthly Charges    7043 non-null   float64
 24  Total Charges      7043 non-null   str
 25  Churn Label        7043 non-null   str
 26  Churn Value        7043 non-null   int64
 27  Churn Score        7043 non-null   int64
 28  CLTV               7043 non-null   int64
 29  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(5), str(22)
memory usage: 1.6 MB

# Creating Machine Learning Dataset

Not all columns are suitable for predictive modeling.

Columns such as CustomerID and Churn Reason either uniquely identify customers or reveal information that would only be known after churn occurs.

These columns are removed to avoid data leakage and improve model generalization.

In [6]:
columns_to_drop = [
    "CustomerID",
    "City",
    "Zip Code",
    "Latitude",
    "Longitude",
    "Lat Long",
    "Churn Score",
    "CLTV",
    "Churn Reason",
    "Churn Label"
]

ml_df = df.drop(columns=columns_to_drop)

In [7]:
ml_df.columns

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months',
       'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Value'],
      dtype='str')

In [8]:
ml_df.shape

(7043, 20)

In [9]:
ml_df.to_csv(
    "../data/processed/ml_dataset.csv",
    index=False
)

# Separating Features and Target Variable

The target variable for this project is:

**Churn Value**

0 → Customer Retained

1 → Customer Churned

In [10]:
X = ml_df.drop("Churn Value", axis=1)

y = ml_df["Churn Value"]

In [11]:
X.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3

In [12]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Churn Value, dtype: int64

# Encoding Categorical Variables

Machine learning algorithms require numerical input.

Categorical features are converted into numerical values using Label Encoding.

In [13]:
encoder = LabelEncoder()

In [14]:
categorical_columns = X.select_dtypes(include="object").columns

categorical_columns

C:\Users\Tanvi\AppData\Local\Temp\ipykernel_2528\3696774006.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(include="object").columns

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Total Charges'],
      dtype='str')

In [15]:
for col in categorical_columns:
    X[col] = encoder.fit_transform(X[col])

In [16]:
X.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges
0,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157
1,0,0,0,1,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925
2,0,0,0,1,8,1,2,1,0,0,2,0,2,2,0,1,2,99.65,6104
3,0,0,1,1,28,1,2,1,0,0,2,2,2,2,0,1,2,104.80,2646
4,1,0,0,1,49,1,2,1,0,2,2,0,2,2,0,1,0,103.70,4265

# Train-Test Split

The dataset is divided into training and testing subsets.

Training Set → 80%

Testing Set → 20%

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [18]:
print(X_train.shape)
print(X_test.shape)

(5634, 19)
(1409, 19)

# Feature Scaling

Numerical features are standardized using StandardScaler.

Scaling improves the performance of algorithms such as Logistic Regression.

In [19]:
scaler = StandardScaler()

In [20]:
numerical_columns = [
    "Tenure Months",
    "Monthly Charges",
    "Total Charges"
]

In [21]:
X_train[numerical_columns] = scaler.fit_transform(
    X_train[numerical_columns]
)

X_test[numerical_columns] = scaler.transform(
    X_test[numerical_columns]
)

In [22]:
X_train.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges
4626,1,0,0,0,0.102371,0,1,0,0,0,2,0,2,2,0,0,2,-0.521976,-1.103276
4192,1,0,1,1,-0.711743,1,0,1,2,0,0,0,0,0,0,0,3,0.337478,-1.586278
5457,1,0,1,1,-0.793155,0,1,0,2,2,0,2,0,0,2,0,3,-0.809013,0.825559
4717,0,0,1,0,-0.263980,1,0,0,0,2,2,0,2,2,2,1,1,0.284384,-0.942451
4673,1,0,1,1,-1.281624,1,0,0,0,0,0,0,0,0,0,0,2,-0.676279,0.241513

In [23]:
X_train.to_csv("../data/processed/X_train.csv", index=False)

X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)

y_test.to_csv("../data/processed/y_test.csv", index=False)

# Final Feature Summary

| Feature | Used in ML | Reason |
|-----------|-----------|--------|
| CustomerID | ❌ | Unique Identifier |
| City | ❌ | Used for Dashboard |
| Latitude | ❌ | Used for Dashboard |
| Longitude | ❌ | Used for Dashboard |
| Churn Score | ❌ | Data Leakage |
| CLTV | ❌ | Business Analysis |
| Churn Reason | ❌ | Available only after churn |
| Contract | ✅ | Strong churn predictor |
| Monthly Charges | ✅ | Customer billing behavior |
| Tenure Months | ✅ | Customer loyalty indicator |
| Payment Method | ✅ | Customer payment behavior |

# Preprocessing Summary

The dataset has been successfully prepared for machine learning.

Completed Steps:

- Removed unnecessary columns
- Eliminated data leakage features
- Created machine learning dataset
- Encoded categorical variables
- Separated features and target
- Performed train-test split
- Standardized numerical variables

The processed data is now ready for model development.